// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12T-diKwSjPdK2r6Wx5Vdjn8tyAqpZOU',
    appId: '1:285178143559:web:c507ee175203dda1196262',
    messagingSenderId: '285178143559',
    projectId: 'shoes-project-73b98',
    authDomain: 'shoes-project-73b98.firebaseapp.com',
    storageBucket: 'shoes-project-73b98.appspot.com',
    measurementId: 'G-6BBYDG6HXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5mLTJI-3qFfc-yWu-7z-pHYjaKafiY6Y',
    appId: '1:285178143559:android:81a4899c337aa0e0196262',
    messagingSenderId: '285178143559',
    projectId: 'shoes-project-73b98',
    storageBucket: 'shoes-project-73b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7JWJMG_1KAGl2mGMtaDjObDV334bVa8',
    appId: '1:285178143559:ios:d7dff600f75eeb56196262',
    messagingSenderId: '285178143559',
    projectId: 'shoes-project-73b98',
    storageBucket: 'shoes-project-73b98.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7JWJMG_1KAGl2mGMtaDjObDV334bVa8',
    appId: '1:285178143559:ios:1995bcac011e2661196262',
    messagingSenderId: '285178143559',
    projectId: 'shoes-project-73b98',
    storageBucket: 'shoes-project-73b98.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
